name: CreativeCurve
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13046
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feecd0'
    - '#9a6930'
    - '#fdb860'
    - '#583b1c'
    - '#040000'
  brandStrength: 0.125
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 1
purpose: []
